apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: oca-build-pipeline-run-
spec:
  pipelineRef:
    name: oca-clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  taskRunSpecs:
  - pipelineTaskName: build-push
    taskPodTemplate:
      securityContext:
        runAsUser: 0
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  - name: gh-docker-credentials
    secret:
      secretName: gh-docker-credentials
  - name: git-credentials
    secret:
      secretName: git-credentials
  params:
  - name: repo-url
    value: git@github.com:stanleykao72/oca-ci.git
  - name: revision
    value: "ubuntu-24.04"
  - name: image-reference
    value: ghcr.io/stanleykao72/py3.12-odoo18.0:18.01
  - name: python_version
    value: "3.12"
  - name: odoo_version
    value: "18.0"
  - name: codename
    value: noble
  - name: odoo_org_repo
    value: odoo/odoo