apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: oca-build-pipeline-run-
spec:
  pipelineRef:
    name: oca-build-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  - name: git-credentials
    secret:
      secretName: git-credentials
  params:
  - name: repo-url
    value: git@github.com:stanleykao72/oca-ci.git
  - name: revision
    value: "main"
  - name: api-image
    value: ghcr.io/stanleykao72/oca-ci:main
  - name: web-image
    value: ghcr.io/stanleykao72/oca-ci/py3.12.3-odoo18.0:latest
  - name: python_version
    value: "3.12.3"
  - name: odoo_version
    value: "18.0"
